package com.demo.ms.search.person.api.impl;

import com.demo.ms.search.person.entities.PersonEntity;
import com.demo.ms.search.person.model.Person;

import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import com.demo.ms.search.person.api.PersonController;
import com.demo.ms.search.person.repository.PersonRepository;

@RestController
public class PersonControllerImpl implements PersonController {

    private final PersonRepository personRepository;

    private ModelMapper modelMapper;

    public PersonControllerImpl(
            @Autowired final PersonRepository personRepository,
            @Autowired final ModelMapper modelMapper) {
        this.personRepository = personRepository;
        this.modelMapper = modelMapper;
    }

    @Override
    public ResponseEntity<Person> createNewPerson(final Person person) {
        final PersonEntity personEntity = mapToEntityAndCleanAutoGeneratedData(person);

        final PersonEntity savedPersonEntity = personRepository.saveAndFlush(personEntity);
        final Person savedPerson = modelMapper.map(savedPersonEntity, Person.class);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(savedPerson);
    }

    private PersonEntity mapToEntityAndCleanAutoGeneratedData(final Person person) {
        final PersonEntity personEntity = modelMapper.map(person, PersonEntity.class);
        personEntity.setId(null);
        personEntity.setCreated(null);
        personEntity.setLastUpdate(null);
        return personEntity;
    }
}
